calculator/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    path('',views.calcindex,name='calcindex'),
]

retcalc/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('newuser/',include('usercreation.urls')),
    path('calculate/',include('calculator.urls'))
]

usercreation/urls.py
from django.urls import path,include
from . import views

app_name = 'usercreation'
urlpatterns = [
    path('signup/',views.register,name='signup'),
    path('login/',views.user_login,name='userlogin'),
    path('',views.index,name='index'),
    path('logout/',views.user_logout,name='logout')
]

calculator/models.py
from django.db import models

# Create your models here.

usercreation/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

usercreation/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('profile_pic',)

calculator/views.py
from django.shortcuts import render

# Create your views here.
def calcindex(request):
    return render(request,'calcindex.html')

usercreation/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect
from .forms import UserProfileInfoForm,UserForm

def index(request):
    return render(request,'usercreation/index.html')

# Create your views here.
def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active: 
                login(request,user)
                return HttpResponseRedirect(reverse('usercreation:index'))
            else:
                return HttpResponse('Account not active')

        else:
            print('Someone tried to login and failed')
            print('Username: {} and password: {}'.format(username,password))

            return HttpResponse("Invalid login details")

    else:
        return render(request,'usercreation/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('usercreation:index'))

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            
            profile.save()
            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'usercreation/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Retirement Calculator</title>

    <!-- bootstrap-4 css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <!-- own css -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block extra_head %}
    {% endblock %}
    <!-- google fonts -->
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top techfont">
        <a class="navbar-brand bigbrand" href="">
            <img src="{% static 'images/mortgage_rate.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Retirement Calculator</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/avirupdg17/">GitHub</a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto navbar-right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'usercreation:logout' %}">Log Out</a></li>
            <li><a>Welcome: {{user.username}}</a></li>

            {% else %}
              <li><a href="{% url 'usercreation:userlogin' %}">Hello, Sign In
                <i class="fa-solid fa-user fa-lg "></i></span>
              </a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    
    <div class="sidebar">
        <a href="#">About</a>
        <a href="#">Calculator</a>
        <a href="#">Clients</a>
        <a href="#">Contact</a>
    </div>
      
    <div class="content">
        <div class="container">
                {% block body_block %}
                {% endblock %}
            </div>
        </div>
    </div>  

    
    
    <!-- bootstrap-4 js -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/868b0d7602.js" crossorigin="anonymous"></script>
</body>
</html>

usercreation/templates/usercreation/index.html
{% extends 'base.html' %}
{% load static %}
{% block extra_head %}
    <!-- own css -->
    {% endblock %}

{% block body_block %}
<h2>This is index page</h2>
{% endblock %}

usercreation/templates/usercreation/login.html
{% extends 'base.html' %}
{% load static %}
{% block extra_head %}
    <!-- own css -->
    <link rel="stylesheet" href="{% static 'css/newlogin.css' %}">
    {% endblock %}

{% block body_block %}
<div class="jumbotron loginform">
    <h1 style="text-align:center">Please Login</h1>
    <hr>
    <form action="{% url 'usercreation:userlogin' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="username">Enter your username: </label>
          <input type="text" class="form-control" aria-describedby="userHelp" placeholder="Enter username" name="username">
        </div>
        <div class="form-group">
          <label for="password">Password: </label>
          <input type="password" class="form-control" placeholder="Password" name="password">
        </div>
        <div class="text-center">
            <input type="submit" value="Login" class="btn btn-success"> 
        </div> 
    </form>
</div>
<hr>
<div class="container">
  <div class="row justify-content-sm-center">
    <h6>New to Retirement Calculator?</h6>
  </div>
  <div class="row justify-content-sm-center ">
    <a href="{% url 'usercreation:signup' %}" class="btn btn-primary">Signup</a>
  </div>
</div>
{% endblock %}

usercreation/templates/usercreation/registration.html
{% extends "base.html" %}
{% load static %}
{% block extra_head %}
    <!-- own css -->
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block body_block %}
<div class="jumbotron signupform">
    {% if registered %}
        <h2>Thank you for registering</h2>
    {% else %}
        <h2>Register here!</h2>
        <h3>Fill out the form: </h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p}}
            {{ profile_form.as_p}}
            <input type="submit" value="Register" class="btn btn-primary">
        </form>
    {% endif %}
</div>
{% endblock %}